---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Antools: Analisys tools

<!-- badges: start -->
<!-- badges: end -->

The goal of antools to be a set of tools that serve as a complement to the statistical analyses used in psychology.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("brianmsm/antools")
```


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(antools)
## basic example code
```

```{r cars}
library(lavaan)

HS.model <- " visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 "

fit <- cfa(
  model = HS.model,
  data = HolzingerSwineford1939
)

fit_lavaan(fit)
```

